// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUP1rzF7wUSmOcc8mR86i9sNUthmvGgQE',
    appId: '1:1050594572005:web:2c1cc74fa3d3587f88c60c',
    messagingSenderId: '1050594572005',
    projectId: 'bijlismart-3e371',
    authDomain: 'bijlismart-3e371.firebaseapp.com',
    storageBucket: 'bijlismart-3e371.firebasestorage.app',
    measurementId: 'G-9Q6T3743XV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfHtgwBwAWClDY0NFRVTPXFIjIAkB8hRY',
    appId: '1:1050594572005:android:9a3d30a34016aa3688c60c',
    messagingSenderId: '1050594572005',
    projectId: 'bijlismart-3e371',
    storageBucket: 'bijlismart-3e371.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBClHzjF1yHaeKC8RyVIiHitC5HswFOgNY',
    appId: '1:1050594572005:ios:4eeecf552314065388c60c',
    messagingSenderId: '1050594572005',
    projectId: 'bijlismart-3e371',
    storageBucket: 'bijlismart-3e371.firebasestorage.app',
    iosBundleId: 'com.example.bijlismart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBClHzjF1yHaeKC8RyVIiHitC5HswFOgNY',
    appId: '1:1050594572005:ios:4eeecf552314065388c60c',
    messagingSenderId: '1050594572005',
    projectId: 'bijlismart-3e371',
    storageBucket: 'bijlismart-3e371.firebasestorage.app',
    iosBundleId: 'com.example.bijlismart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUP1rzF7wUSmOcc8mR86i9sNUthmvGgQE',
    appId: '1:1050594572005:web:309a65c59fb4844788c60c',
    messagingSenderId: '1050594572005',
    projectId: 'bijlismart-3e371',
    authDomain: 'bijlismart-3e371.firebaseapp.com',
    storageBucket: 'bijlismart-3e371.firebasestorage.app',
    measurementId: 'G-F0LLZC4TFV',
  );
}
